Feat / Follow & unfollow users
undefined-ims-india/mkdev pull request #51
Opened 2024-06-17 14:44 UTC by cody-daigle

2024-06-17 21:37 UTC, mikesamm approved these changes

2024-06-18 14:08 UTC, AlexPHebert2000 commented on client/src/components/UserProfile.tsx
> +            alt={profileData!.username ? profileData!.name : ''}
This checks if the **username** exists and sets the alt to the **name** or an empty string. This doesn't make much sense to me.

2024-06-18 14:23 UTC, AlexPHebert2000 commented on server/routes/routers/follows.ts
In this file, when you do your get request you can use [Select](https://www.prisma.io/docs/orm/prisma-client/queries/select-fields) in your queries since you dont need all the information, probably just the id, username and picture

2024-06-18 14:24 UTC, AlexPHebert2000 requested changes
See above

2024-06-19 00:19 UTC, AlexPHebert2000 approved these changes

2024-06-19 00:44 UTC, merged