FIX / follower-following button and info
undefined-ims-india/mkdev pull request #64
Opened 2024-06-19 21:31 UTC by cody-daigle

2024-06-20 18:42 UTC, mikesamm approved these changes

2024-06-20 21:43 UTC, AlexPHebert2000 commented on .vscode/settings.json
Did you mean to commit your vscode settings?

2024-06-20 21:45 UTC, AlexPHebert2000 commented on client/src/components/Following.tsx
> +      console.log(data);
Please remove debug log

2024-06-20 21:49 UTC, AlexPHebert2000 requested changes
Remove console log

2024-06-21 16:14 UTC, AlexPHebert2000 approved these changes

2024-06-21 16:14 UTC, merged