FIX / Navbar
undefined-ims-india/mkdev pull request #89
Opened 2024-07-01 19:00 UTC by AlexPHebert2000

2024-07-01 20:12 UTC, cody-daigle approved these changes

2024-07-02 02:21 UTC, mikesamm requested changes

2024-07-02 02:21 UTC, mikesamm commented on client/src/components/App.tsx
> +            {['/dashboard', '/', '/survey'].includes(location.pathname) ? <></> : <Nav />}\
I dig this ternary expression.

2024-07-02 02:21 UTC, mikesamm commented on server/index.ts
> +console.log(PUBLIC)
Are you actively using this? If not, please remove.

2024-07-02 13:58 UTC, mikesamm approved these changes

2024-07-02 13:58 UTC, merged